/**
 * `adjudicate dev` — local dev harness over Docker Compose.
 *
 * Brings up the two services every adjudicate-based system needs in
 * development: Redis (DeferStore / rate limiting) and Postgres (audit
 * sink). The Operator Console is included in the generated compose
 * file but commented out by default — it requires a build pass first
 * and most adopters run the console directly via `pnpm dev`.
 *
 * Generates `docker-compose.dev.yml` in cwd on first run; subsequent
 * invocations reuse it. Adopters who want to customize (different
 * ports, additional services) edit the generated file directly — the
 * CLI never overwrites an existing file.
 *
 * Subcommands:
 *   adjudicate dev            → docker compose up -d
 *   adjudicate dev --stop     → docker compose down
 *   adjudicate dev --logs     → docker compose logs -f
 *
 * If `docker` is missing from $PATH, the command exits with a helpful
 * message — it does NOT crash with an ENOENT trace.
 */

import { spawnSync, type SpawnSyncOptions } from "node:child_process";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import chalk from "chalk";

export interface DevOptions {
  /** Stop services. */
  readonly stop?: boolean;
  /** Tail logs. */
  readonly logs?: boolean;
  /** Test injection. Defaults to `process.cwd()`. */
  readonly cwd?: string;
  /** Test injection. Defaults to `process.stdout.write`. */
  readonly stdout?: (line: string) => void;
  /** Test injection. Replaces spawnSync. */
  readonly spawn?: (cmd: string, args: string[], opts: SpawnSyncOptions) => {
    readonly status: number | null;
    readonly error?: Error;
  };
  /**
   * Test injection. When supplied, controls whether `docker` is
   * considered available without actually probing $PATH.
   */
  readonly dockerCheck?: () => boolean;
}

export const COMPOSE_FILENAME = "docker-compose.dev.yml";

const COMPOSE_TEMPLATE = `# Generated by \`adjudicate dev\`.
# Edit freely — \`adjudicate dev\` will NOT overwrite an existing file.
#
# Services:
#   redis     6379  — DeferStore + rate-limit backing
#   postgres  5432  — audit sink (database "adjudicate")
#   console   5180  — operator console (commented; requires build)

services:
  redis:
    image: redis:7-alpine
    container_name: adjudicate-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: adjudicate-postgres
    environment:
      POSTGRES_USER: adjudicate
      POSTGRES_PASSWORD: adjudicate
      POSTGRES_DB: adjudicate
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adjudicate"]
      interval: 5s
      timeout: 3s
      retries: 5

  # console:
  #   build:
  #     context: ./apps/console
  #   container_name: adjudicate-console
  #   ports:
  #     - "5180:5180"
  #   environment:
  #     DATABASE_URL: postgres://adjudicate:adjudicate@postgres:5432/adjudicate
  #     REDIS_URL: redis://redis:6379
  #   depends_on:
  #     - postgres
  #     - redis
`;

export async function runDev(options: DevOptions): Promise<void> {
  const cwd = options.cwd ?? process.cwd();
  const out =
    options.stdout ?? ((line: string) => process.stdout.write(`${line}\n`));
  const spawn = options.spawn ?? defaultSpawn;
  const dockerCheck = options.dockerCheck ?? defaultDockerCheck;

  if (!dockerCheck()) {
    out(
      chalk.red("✗") +
        " `docker` not found on PATH. Install Docker Desktop or your distro's Docker package.",
    );
    out(
      chalk.dim(
        "  Once Docker is available, re-run `adjudicate dev` to spin up Redis + Postgres.",
      ),
    );
    process.exit(1);
  }

  const composePath = path.join(cwd, COMPOSE_FILENAME);
  // Generate compose file on first run; never overwrite (adopters
  // freely edit it to add their own services).
  if (!(await exists(composePath))) {
    await fs.writeFile(composePath, COMPOSE_TEMPLATE, "utf8");
    out(chalk.dim("•") + ` Generated ${COMPOSE_FILENAME}`);
  }

  const composeArgs = ["compose", "-f", COMPOSE_FILENAME];

  if (options.stop) {
    out(chalk.dim("• ") + "docker compose down");
    const result = spawn("docker", [...composeArgs, "down"], {
      stdio: "inherit",
      cwd,
    });
    handleResult(result, out);
    return;
  }

  if (options.logs) {
    out(chalk.dim("• ") + "docker compose logs -f");
    const result = spawn("docker", [...composeArgs, "logs", "-f"], {
      stdio: "inherit",
      cwd,
    });
    handleResult(result, out);
    return;
  }

  out(chalk.dim("• ") + "docker compose up -d");
  const result = spawn("docker", [...composeArgs, "up", "-d"], {
    stdio: "inherit",
    cwd,
  });
  handleResult(result, out);
  if ((result.status ?? 0) === 0) {
    out("");
    out(chalk.green("✓") + " Services started.");
    out(
      chalk.dim("  redis    : redis://localhost:6379"),
    );
    out(
      chalk.dim("  postgres : postgres://adjudicate:adjudicate@localhost:5432/adjudicate"),
    );
    out(chalk.dim("  Tail logs with `adjudicate dev --logs`."));
    out(chalk.dim("  Tear down with `adjudicate dev --stop`."));
  }
}

function handleResult(
  result: { status: number | null; error?: Error },
  out: (line: string) => void,
): void {
  if (result.error) {
    out(chalk.red("✗") + ` docker invocation failed: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    out(chalk.red("✗") + ` docker exited with status ${result.status}.`);
    process.exit(result.status ?? 1);
  }
}

function defaultSpawn(
  cmd: string,
  args: string[],
  opts: SpawnSyncOptions,
): { status: number | null; error?: Error } {
  const r = spawnSync(cmd, args, opts);
  return { status: r.status, error: r.error };
}

function defaultDockerCheck(): boolean {
  const r = spawnSync("docker", ["--version"], { stdio: "ignore" });
  // spawnSync returns r.error for ENOENT; r.status is null in that case.
  return !r.error && r.status === 0;
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
