import { describe, expect, it } from "vitest";
import { assertPackConformance } from "@adjudicate/core";
import { IdentityKycPack } from "../src/index.js";

/**
 * Conformance test — runs the kernel's `assertPackConformance` against
 * the Pack export. Generated by `adjudicate pack init` (Phase 3a) and
 * extended for the KYC intent vocabulary (Phase 3b). The async
 * lifecycle behaviors are covered separately in `kyc.test.ts`; this
 * file is the structural floor.
 */
describe("pack-identity-kyc — conformance", () => {
  it("passes kernel pack conformance", () => {
    expect(() => assertPackConformance(IdentityKycPack)).not.toThrow();
  });

  it("declares the three KYC intent kinds", () => {
    expect(IdentityKycPack.intents).toContain("kyc.start");
    expect(IdentityKycPack.intents).toContain("kyc.document.upload");
    expect(IdentityKycPack.intents).toContain("kyc.vendor.callback");
    expect(IdentityKycPack.intents).toHaveLength(3);
  });

  it("uses contract v0", () => {
    expect(IdentityKycPack.contract).toBe("v0");
  });

  it("declares basisCodes that the policy may emit", () => {
    expect(IdentityKycPack.basisCodes.length).toBeGreaterThan(0);
    expect(IdentityKycPack.basisCodes).toContain(
      "kyc.verification_score_too_low",
    );
  });

  it("declares the two DEFER signals (kyc.documents.uploaded + kyc.vendor.completed)", () => {
    expect(IdentityKycPack.signals).toContain("kyc.documents.uploaded");
    expect(IdentityKycPack.signals).toContain("kyc.vendor.completed");
  });

  it("has 5 business guards (2 DEFER + 3 terminal)", () => {
    expect(IdentityKycPack.policy.business).toHaveLength(5);
  });

  it("uses default=REFUSE for conservative-by-default semantics", () => {
    expect(IdentityKycPack.policy.default).toBe("REFUSE");
  });
});
