// GENERATED by scripts/count-stats.ts — do not edit by hand
// Run `pnpm stats` (or `pnpm prebuild`) to refresh from the live repo.

export const STATS = {
  packages: 25,
  adrs: 36,
  tests: 225,
  capabilities: 14,
  outcomes: 6,
} as const;

export type Stats = typeof STATS;
