/**
 * count-stats.ts
 *
 * Counts real artefacts from the monorepo and emits a typed, generated module
 * at src/content/stats.generated.ts. Run via `pnpm stats` or automatically on
 * `prebuild`, so the homepage social-proof numbers are NEVER hardcoded.
 *
 * Resolves the repo root relative to this file (apps/web/scripts -> ../../..).
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "../../..");

/** Non-countable constants that define the kernel's shape. */
const CAPABILITIES = 14;
const OUTCOMES = 6;

/** Directory names we never descend into while walking the tree. */
const SKIP_DIRS = new Set([
  "node_modules",
  ".next",
  ".git",
  "dist",
  "build",
  "coverage",
]);

/** Count immediate subdirectories of `dir` (the package roots). */
function countDirEntries(dir: string): number {
  let count = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory() && !SKIP_DIRS.has(entry.name)) {
      count += 1;
    }
  }
  return count;
}

/** Count files directly under `dir` whose name matches `pattern`. */
function countFilesMatching(dir: string, pattern: RegExp): number {
  let count = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isFile() && pattern.test(entry.name)) {
      count += 1;
    }
  }
  return count;
}

/** Recursively count files whose name matches `pattern`, skipping SKIP_DIRS. */
function countFilesRecursive(dir: string, pattern: RegExp): number {
  let count = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      count += countFilesRecursive(join(dir, entry.name), pattern);
    } else if (entry.isFile() && pattern.test(entry.name)) {
      count += 1;
    }
  }
  return count;
}

function dirExists(path: string): boolean {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

const packagesDir = join(REPO_ROOT, "packages");
const adrDir = join(REPO_ROOT, "docs", "architecture", "adr");
const appsDir = join(REPO_ROOT, "apps");

const packages = dirExists(packagesDir) ? countDirEntries(packagesDir) : 0;

const adrs = dirExists(adrDir)
  ? countFilesMatching(adrDir, /^ADR-.*/i)
  : 0;

const testPattern = /\.test\.ts$/;
const tests =
  (dirExists(packagesDir) ? countFilesRecursive(packagesDir, testPattern) : 0) +
  (dirExists(appsDir) ? countFilesRecursive(appsDir, testPattern) : 0);

const STATS = {
  packages,
  adrs,
  tests,
  capabilities: CAPABILITIES,
  outcomes: OUTCOMES,
} as const;

const banner =
  "// GENERATED by scripts/count-stats.ts — do not edit by hand";

const body = `${banner}
// Run \`pnpm stats\` (or \`pnpm prebuild\`) to refresh from the live repo.

export const STATS = {
  packages: ${STATS.packages},
  adrs: ${STATS.adrs},
  tests: ${STATS.tests},
  capabilities: ${STATS.capabilities},
  outcomes: ${STATS.outcomes},
} as const;

export type Stats = typeof STATS;
`;

const outPath = join(SCRIPT_DIR, "..", "src", "content", "stats.generated.ts");
writeFileSync(outPath, body, "utf8");

// eslint-disable-next-line no-console
console.log(
  `stats.generated.ts written: ${JSON.stringify(STATS)} -> ${outPath}`,
);
