/**
 * {{packName}} — adjudicate KYC Pack.
 *
 * Generated by `adjudicate pack init {{packName}} --template kyc`.
 *
 * Exercises four Decision outcomes against a KYC session lifecycle:
 * REFUSE (session missing), ESCALATE (low vendor score), DEFER
 * (awaiting documents / vendor), EXECUTE (vendor callback / complete).
 * Customize guards in `./policy.ts` for your domain.
 */

import type { PackV0 } from "@adjudicate/core";
import { {{className}}CapabilityPlanner } from "./capabilities.js";
import { {{className}}PolicyBundle } from "./policy.js";
import {
  KYC_DOCUMENTS_UPLOADED_SIGNAL,
  KYC_VENDOR_COMPLETED_SIGNAL,
  type {{className}}Context,
  type {{className}}IntentKind,
  type {{className}}State,
} from "./types.js";

export const {{className}}Pack = {
  id: "{{packName}}",
  version: "0.1.0-experimental",
  contract: "v0",
  intents: [
    "{{intentPrefix}}.kyc.start",
    "{{intentPrefix}}.kyc.document.upload",
    "{{intentPrefix}}.kyc.vendor.callback",
    "{{intentPrefix}}.kyc.complete",
  ],
  policy: {{className}}PolicyBundle,
  planner: {{className}}CapabilityPlanner,
  basisCodes: [
    "{{intentPrefix}}.kyc.session_missing",
    "{{intentPrefix}}.kyc.score_too_low",
  ],
  signals: [KYC_DOCUMENTS_UPLOADED_SIGNAL, KYC_VENDOR_COMPLETED_SIGNAL],
} as const satisfies PackV0<
  {{className}}IntentKind,
  unknown,
  {{className}}State,
  {{className}}Context
>;

export type {
  {{className}}Context,
  {{className}}IntentKind,
  {{className}}KycSession,
  {{className}}KycStatus,
  {{className}}State,
} from "./types.js";

export {
  ESCALATE_LOW_SCORE_THRESHOLD,
  KYC_DEFAULT_DEFER_TIMEOUT_MS,
  KYC_DOCUMENTS_UPLOADED_SIGNAL,
  KYC_VENDOR_COMPLETED_SIGNAL,
  {{className}}TaintPolicy,
} from "./types.js";

export { {{className}}PolicyBundle } from "./policy.js";
export { {{className}}CapabilityPlanner, {{className}}Tools } from "./capabilities.js";
