/**
 * {{className}} KYC domain — types and taint policy.
 *
 * A know-your-customer Pack tracks an identity-verification session
 * through stages: start → documents_pending → vendor_pending →
 * completed | rejected. The TaintPolicy ensures `vendor.callback`
 * arrives from the vendor's authenticated webhook (TRUSTED) and never
 * an LLM. Vendor scores below a threshold ESCALATE for human review.
 *
 * Generated by `adjudicate pack init {{packName}} --template kyc`.
 */

import { createSystemTaintPolicy } from "@adjudicate/primitives";

// ─── Intent kinds ──────────────────────────────────────────────────────────

export type {{className}}IntentKind =
  | "{{intentPrefix}}.kyc.start"
  | "{{intentPrefix}}.kyc.document.upload"
  | "{{intentPrefix}}.kyc.vendor.callback"
  | "{{intentPrefix}}.kyc.complete";

// ─── Payloads ──────────────────────────────────────────────────────────────

export interface {{className}}KycStartPayload {
  readonly userId: string;
}

export interface {{className}}KycDocumentUploadPayload {
  readonly sessionId: string;
  readonly documentType: "passport" | "id_card" | "drivers_license";
  /** Opaque vendor-side document reference. */
  readonly documentRef: string;
}

export interface {{className}}KycVendorCallbackPayload {
  readonly sessionId: string;
  /** Vendor's risk/quality score 0..100. */
  readonly score: number;
  readonly vendorReference: string;
}

export interface {{className}}KycCompletePayload {
  readonly sessionId: string;
}

// ─── State ─────────────────────────────────────────────────────────────────

export type {{className}}KycStatus =
  | "init"
  | "documents_pending"
  | "vendor_pending"
  | "completed"
  | "rejected";

export interface {{className}}KycSession {
  readonly id: string;
  readonly userId: string;
  readonly status: {{className}}KycStatus;
  readonly score?: number;
}

export interface {{className}}State {
  /** Active KYC session, or null if none. Single-session model for clarity. */
  readonly session: {{className}}KycSession | null;
}

// ─── Context ───────────────────────────────────────────────────────────────

export interface {{className}}Context {
  readonly tenantId: string;
}

// ─── Taint policy ──────────────────────────────────────────────────────────
//
// `vendor.callback` arrives from the KYC vendor's authenticated webhook
// — SYSTEM-only. All other intents tolerate UNTRUSTED.

export const {{className}}TaintPolicy = createSystemTaintPolicy({
  systemOnlyKinds: ["{{intentPrefix}}.kyc.vendor.callback"],
});

// ─── Domain constants ──────────────────────────────────────────────────────

/**
 * Sessions whose vendor score is BELOW this threshold ESCALATE for
 * manual review.
 */
export const ESCALATE_LOW_SCORE_THRESHOLD = 30;

export const KYC_DOCUMENTS_UPLOADED_SIGNAL = "kyc.documents.uploaded";
export const KYC_VENDOR_COMPLETED_SIGNAL = "kyc.vendor.completed";
export const KYC_DEFAULT_DEFER_TIMEOUT_MS = 30 * 60 * 1000;
