import { describe, expect, it } from "vitest";
import { assertPackConformance } from "@adjudicate/core";
import { {{className}}Pack } from "../src/index.js";

/**
 * Conformance test — runs the kernel's `assertPackConformance` against
 * the Pack export. Generated by `adjudicate pack init`; this test is
 * the floor. Add domain-specific tests alongside as your Pack grows
 * (e.g., a `six-outcomes.test.ts` to exercise every Decision kind, or
 * a `defer-round-trip.test.ts` if your Pack uses DEFER signals — see
 * pack-payments-pix for both patterns).
 */
describe("{{packName}} — conformance", () => {
  it("passes kernel pack conformance", () => {
    expect(() => assertPackConformance({{className}}Pack)).not.toThrow();
  });

  it("declares the expected intent kinds", () => {
    expect({{className}}Pack.intents).toContain(
      "{{intentPrefix}}.demo.create",
    );
    expect({{className}}Pack.intents).toContain(
      "{{intentPrefix}}.demo.confirm",
    );
  });

  it("uses contract v0", () => {
    expect({{className}}Pack.contract).toBe("v0");
  });

  it("declares basisCodes that the policy may emit", () => {
    expect({{className}}Pack.basisCodes.length).toBeGreaterThan(0);
  });

  it("has a non-empty business guard list", () => {
    expect({{className}}Pack.policy.business.length).toBeGreaterThan(0);
  });
});
