{
  "name": "{{packName}}",
  "version": "0.1.0-experimental",
  "description": "adjudicate Pack — generated by `adjudicate pack init {{packName}}`. Customize for your domain.",
  "type": "module",
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js",
      "default": "./dist/index.js"
    }
  },
  "scripts": {
    "build": "tsc --outDir dist",
    "lint": "tsc --noEmit",
    "test": "vitest run"
  },
  "dependencies": {
    "@adjudicate/core": "workspace:*"
  },
  "devDependencies": {
    "typescript": "^5.9.0",
    "vitest": "^3.2.0"
  }
}
