/**
 * {{packName}} — adjudicate approval Pack.
 *
 * Generated by `adjudicate pack init {{packName}} --template approval`.
 *
 * Exercises four Decision outcomes against a multi-stage approval
 * surface: REFUSE (self-approval), ESCALATE (above threshold), DEFER
 * (awaiting supervisor), EXECUTE (non-self approve/deny). Customize
 * guards in `./policy.ts` for your domain.
 */

import type { PackV0 } from "@adjudicate/core";
import { {{className}}CapabilityPlanner } from "./capabilities.js";
import { {{className}}PolicyBundle } from "./policy.js";
import {
  APPROVAL_GRANTED_SIGNAL,
  type {{className}}Context,
  type {{className}}IntentKind,
  type {{className}}State,
} from "./types.js";

export const {{className}}Pack = {
  id: "{{packName}}",
  version: "0.1.0-experimental",
  contract: "v0",
  intents: [
    "{{intentPrefix}}.approval.request",
    "{{intentPrefix}}.approval.approve",
    "{{intentPrefix}}.approval.deny",
  ],
  policy: {{className}}PolicyBundle,
  planner: {{className}}CapabilityPlanner,
  basisCodes: [
    "{{intentPrefix}}.approval.self_approval_forbidden",
    "{{intentPrefix}}.approval.request_not_found",
  ],
  signals: [APPROVAL_GRANTED_SIGNAL],
} as const satisfies PackV0<
  {{className}}IntentKind,
  unknown,
  {{className}}State,
  {{className}}Context
>;

export type {
  {{className}}ApprovalRequest,
  {{className}}ApprovalStatus,
  {{className}}Approver,
  {{className}}Context,
  {{className}}IntentKind,
  {{className}}State,
} from "./types.js";

export {
  APPROVAL_GRANTED_SIGNAL,
  APPROVAL_DEFAULT_DEFER_TIMEOUT_MS,
  ESCALATE_AMOUNT_THRESHOLD,
  {{className}}TaintPolicy,
} from "./types.js";

export { {{className}}PolicyBundle } from "./policy.js";
export { {{className}}CapabilityPlanner, {{className}}Tools } from "./capabilities.js";
