/**
 * {{className}} approval domain — types and taint policy.
 *
 * A multi-stage approval Pack covers a request → approve/deny lifecycle
 * with separation of duties (no self-approval) and threshold-based
 * escalation. The state holds the current pending request plus the
 * acting approver's role/id; the TaintPolicy ensures approve/deny
 * intents only flow from TRUSTED actors.
 *
 * Generated by `adjudicate pack init {{packName}} --template approval`.
 */

import { createSystemTaintPolicy } from "@adjudicate/primitives";

// ─── Intent kinds ──────────────────────────────────────────────────────────

export type {{className}}IntentKind =
  | "{{intentPrefix}}.approval.request"
  | "{{intentPrefix}}.approval.approve"
  | "{{intentPrefix}}.approval.deny";

// ─── Payloads ──────────────────────────────────────────────────────────────

export interface {{className}}ApprovalRequestPayload {
  /** Identifier of the principal initiating the request. */
  readonly requestedBy: string;
  /** Numeric amount (centavos, headcount, etc.) the policy compares against. */
  readonly amount: number;
  /** Free-text reason — surfaced to approvers. */
  readonly reason: string;
}

export interface {{className}}ApprovalApprovePayload {
  readonly requestId: string;
  readonly comment?: string;
}

export interface {{className}}ApprovalDenyPayload {
  readonly requestId: string;
  readonly reason: string;
}

// ─── State ─────────────────────────────────────────────────────────────────

export type {{className}}ApprovalStatus =
  | "pending"
  | "approved"
  | "denied";

export interface {{className}}ApprovalRequest {
  readonly id: string;
  readonly requestedBy: string;
  readonly amount: number;
  readonly status: {{className}}ApprovalStatus;
}

export interface {{className}}Approver {
  readonly id: string;
  readonly role: "approver" | "supervisor" | "admin";
}

export interface {{className}}State {
  readonly approver: {{className}}Approver;
  /** The single pending request, or null. Adopters often track many. */
  readonly request: {{className}}ApprovalRequest | null;
}

// ─── Context ───────────────────────────────────────────────────────────────

export interface {{className}}Context {
  readonly tenantId: string;
}

// ─── Taint policy ──────────────────────────────────────────────────────────
//
// `approve` and `deny` must arrive from TRUSTED actors (the operator who
// is signed in), never an LLM proposing on their behalf. `request` may
// be UNTRUSTED — the LLM proposes a draft, the policy decides.

export const {{className}}TaintPolicy = createSystemTaintPolicy({
  systemOnlyKinds: [
    "{{intentPrefix}}.approval.approve",
    "{{intentPrefix}}.approval.deny",
  ],
});

// ─── Domain constants ──────────────────────────────────────────────────────

/**
 * Requests at or above this `amount` ESCALATE to a supervisor regardless
 * of the local approver's role.
 */
export const ESCALATE_AMOUNT_THRESHOLD = 10_000;

/**
 * Signal name a deferred `approval.request` parks on.
 */
export const APPROVAL_GRANTED_SIGNAL = "approval.granted";

/**
 * Default deadline for a pending request before adopters expire it.
 */
export const APPROVAL_DEFAULT_DEFER_TIMEOUT_MS = 24 * 60 * 60 * 1000;
