import type { PackV0 } from "@adjudicate/core";
import {
  policy,
  planner,
  type {{className}}Context,
  type {{className}}IntentKind,
  type {{className}}State,
} from "./policy.js";

/**
 * {{packName}} — adjudicate Pack.
 *
 * Generated by `adjudicate discover` from an MCP server's `tools/list`.
 * Every discovered tool became a MUTATING intent kind gated by a REFUSE
 * guard, with `policy.default = "REFUSE"`. The Pack is deny-by-default:
 * it passes conformance but authorizes nothing until you replace the
 * generated stubs with real domain logic. See ./policy.ts.
 */
export const {{className}}Pack = {
  id: "{{packName}}",
  version: "0.1.0-experimental",
  contract: "v0",
  intents: [
{{packIntentsBlock}}
  ],
  policy,
  planner,
  basisCodes: [
    // Refusal codes the generated guards emit. A non-empty list is
    // mandatory — boot-time conformance rejects an empty `basisCodes`.
    // Keep in sync with the codes emitted by the guards in `policy.ts`.
{{basisCodesBlock}}
  ],
} as const satisfies PackV0<
  {{className}}IntentKind,
  unknown,
  {{className}}State,
  {{className}}Context
>;

export type {
  {{className}}Context,
  {{className}}IntentKind,
  {{className}}State,
} from "./policy.js";
