import {
  basis,
  BASIS_CODES,
  decisionRefuse,
  refuse,
  type Guard,
  type PolicyBundle,
  type TaintPolicy,
} from "@adjudicate/core";
import {
  filterReadOnly,
  safePlan,
  type CapabilityPlanner,
  type ToolClassification,
} from "@adjudicate/core/llm";

/**
 * {{className}} — generated by `adjudicate discover` from an MCP server's
 * `tools/list`.
 *
 * SECURITY POSTURE — this is a SCAFFOLD, not a finished policy:
 *
 *   - Every discovered MCP tool is classified MUTATING. `discover`
 *     cannot know whether a tool is side-effect-free, so it assumes the
 *     dangerous case. Re-classify genuinely read-only tools as READ_ONLY
 *     and expose them through the planner once you have verified them.
 *   - `policy.default` is REFUSE and every generated guard REFUSES. The
 *     Pack therefore authorizes NOTHING out of the box — it is a
 *     deny-by-default skeleton. Replace each `refuse*` guard with your
 *     real domain logic (EXECUTE / REWRITE / ESCALATE / DEFER) as you
 *     wire each tool up.
 *   - Every mutating intent requires TRUSTED taint, so LLM-proposed
 *     (UNTRUSTED) envelopes can never reach the business guards.
 */

// ─── Domain types ──────────────────────────────────────────────────────────

export type {{className}}IntentKind =
{{intentKindUnionBlock}};

export interface {{className}}State {
  /** Replace with the real state shape your guards inspect. */
  readonly entities: ReadonlyMap<string, unknown>;
}

export interface {{className}}Context {
  /** Adopter-supplied request context — tenancy, locale, principal id, etc. */
  readonly tenantId: string;
}

// ─── Tool classification ───────────────────────────────────────────────────
//
// Every discovered MCP tool is MUTATING by default (see posture note
// above). `safePlan` enforces that no MUTATING tool leaks into the
// planner's `visibleReadTools` — load-bearing security.

const TOOLS: ToolClassification = {
  // Re-classify a tool here once you have verified it is side-effect-free.
  READ_ONLY: new Set<string>([]),
  MUTATING: new Set<string>([
{{toolClassificationBlock}}
  ]),
};

// ─── Capability planner ────────────────────────────────────────────────────
//
// The scaffold exposes NO read tools and allows NO intents — the safest
// possible plan. Open this up deliberately as you classify tools and
// author guards.

const rawPlanner: CapabilityPlanner<{{className}}State, {{className}}Context> = {
  plan(_state, _context) {
    return {
      visibleReadTools: filterReadOnly(TOOLS, []),
      allowedIntents: [],
    };
  },
};

export const planner = safePlan(rawPlanner, TOOLS);

// ─── Taint policy ──────────────────────────────────────────────────────────
//
// Every mutating intent requires TRUSTED taint. LLM-proposed (UNTRUSTED)
// envelopes are refused at the taint gate before any business guard runs.

const taint: TaintPolicy = {
  minimumFor() {
    return "TRUSTED";
  },
};

// ─── Guards ────────────────────────────────────────────────────────────────
//
// One REFUSE guard per discovered tool. Each emits a declared domain
// refusal code (see `basisCodes` in index.ts). Replace with real logic.

{{guardsBlock}}

// ─── PolicyBundle ──────────────────────────────────────────────────────────

export const policy: PolicyBundle<
  {{className}}IntentKind,
  unknown,
  {{className}}State
> = {
  stateGuards: [],
  authGuards: [],
  taint,
  business: [
{{businessListBlock}}
  ],
  default: "REFUSE",
};
