{
  "name": "{{packName}}",
  "version": "0.1.0-experimental",
  "description": "adjudicate KYC Pack — generated by `adjudicate pack init {{packName}} --template kyc`.",
  "type": "module",
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js",
      "default": "./dist/index.js"
    }
  },
  "scripts": {
    "build": "tsc --outDir dist",
    "lint": "tsc --noEmit",
    "test": "vitest run",
    "test:scenarios": "adjudicate simulate --pack ./dist/index.js --scenarios ./scenarios"
  },
  "files": [
    "dist",
    "scenarios",
    "README.md"
  ],
  "dependencies": {
    "@adjudicate/core": "workspace:*",
    "@adjudicate/primitives": "workspace:*"
  },
  "devDependencies": {
    "@adjudicate/cli": "workspace:*",
    "typescript": "^5.9.0",
    "vitest": "^3.2.0"
  }
}
