import type { PackV0 } from "@adjudicate/core";
import {
  policy,
  planner,
  type {{className}}Context,
  type {{className}}IntentKind,
  type {{className}}State,
} from "./policy.js";

/**
 * {{packName}} — adjudicate Pack.
 *
 * Generated by `adjudicate pack init {{packName}}`. The Pack handles
 * the {{intentPrefix}} domain — see ./policy.ts for the intent kinds,
 * guards, taint policy, and capability planner this Pack ships with.
 *
 * The generated stubs are minimal placeholders that exercise the
 * conformance contract but make no real domain decisions. Replace
 * them with your actual policy logic. The split between this file
 * (Pack metadata) and `policy.ts` (logic) is the canonical layout —
 * adopters with finer-grained organization can split policy.ts into
 * separate types/guards/planner/refusals files (see
 * pack-payments-pix for the reference layout).
 */
export const {{className}}Pack = {
  id: "{{packName}}",
  version: "0.1.0-experimental",
  contract: "v0",
  intents: [
    "{{intentPrefix}}.demo.create",
    "{{intentPrefix}}.demo.confirm",
  ],
  policy,
  planner,
  basisCodes: [
    // Vocabulary the policy may emit. Keep in sync with the codes
    // emitted by guards in `policy.ts`. The kernel's `withBasisAudit`
    // flags emissions outside this list as drift.
    "{{intentPrefix}}.demo.created",
    "{{intentPrefix}}.demo.confirmed",
  ],
} as const satisfies PackV0<
  {{className}}IntentKind,
  unknown,
  {{className}}State,
  {{className}}Context
>;

export type {
  {{className}}Context,
  {{className}}IntentKind,
  {{className}}State,
} from "./policy.js";
