"use client";

import { motion, useReducedMotion } from "framer-motion";
import {
  CircleCheck,
  Clock,
  HelpCircle,
  RotateCcw,
  ShieldX,
  UserCheck,
  type LucideIcon,
} from "lucide-react";

/**
 * HowItWorks — the conceptual story (Tier 0b: scroll-triggered detail).
 *
 * Six frames threaded by one concrete scenario: a deployment proposed at
 * 100% production ramp, intercepted by the kernel, REWRITTEN to 25%, and
 * audited. The same envelope follows the visitor from Frame 2 (the pain)
 * through Frame 6 (the audit record).
 *
 * Phase 1 ships the scroll detail only. The Remotion sizzle (Tier 0a)
 * lands in Phase 2; the slot at the top of this section is reserved for
 * the <video> element when that work begins.
 *
 * Discipline: vocabulary leads with visitor-first terms ("control layer",
 * "requested action") and switches to internal vocabulary ("kernel",
 * "intent") once the visitor has seen the mechanism. Frame 4 animates one
 * branch at a time; REWRITE gets the longest beat as the iconic decision.
 */
export function HowItWorks() {
  return (
    <section id="how-it-works" className="bg-canvas">
      {/* Bridge sentence between Hero and the story */}
      <div className="mx-auto max-w-3xl px-6 pt-20 text-center">
        <p className="text-2xl font-semibold leading-snug text-ink md:text-3xl">
          LLMs generate possibilities.
          <br />
          <span className="bg-gradient-primary bg-clip-text text-transparent">
            Production systems require decisions.
          </span>
        </p>
        <p className="mt-4 text-sm uppercase tracking-section text-muted">
          Scroll to see what sits between them.
        </p>
      </div>

      {/* Sizzle reel (Tier 0a). 10-second autoplay loop, muted, no controls.
          Generated by Remotion at apps/web/video/HowItWorksHero.tsx.
          Prefers-reduced-motion swaps to the poster image with same alt. */}
      <SizzleReel />

      {/* The six frames */}
      <Frame1 />
      <Frame2 />
      <Frame3 />
      <Frame4 />
      <Frame5 />
      <Frame6 />

      {/* Closing CTA */}
      <div className="mx-auto max-w-3xl px-6 pb-24 pt-12 text-center">
        <p className="text-lg text-muted">
          You&apos;ve seen the mechanism. Now run it against the real kernel
          with the real Packs.
        </p>
        <a
          href="/playground"
          className="mt-6 inline-flex items-center gap-2 rounded-full bg-gradient-primary px-7 py-3 text-base font-medium text-white shadow-lg transition-shadow hover:shadow-xl"
        >
          Try it in the playground →
        </a>
      </div>
    </section>
  );
}

// ── Sizzle reel (Tier 0a) ──────────────────────────────────────────────

const SIZZLE_ALT =
  "Animated demonstration of the kernel intercepting an AI-proposed action and producing one of six decisions, ending with an audit record.";

function SizzleReel() {
  const reduce = useReducedMotion();
  return (
    <div className="mx-auto mt-10 max-w-4xl px-6">
      <div className="overflow-hidden rounded-2xl border border-edge bg-surface shadow-lg">
        {reduce ? (
          <img
            src="/how-it-works-poster.jpg"
            alt={SIZZLE_ALT}
            className="block h-auto w-full"
          />
        ) : (
          <video
            autoPlay
            muted
            loop
            playsInline
            poster="/how-it-works-poster.jpg"
            aria-label={SIZZLE_ALT}
            className="block h-auto w-full bg-canvas"
          >
            {/* MP4 first (universal H.264 support); WebM second.
                Browsers don't auto-fall-through after a decode error,
                so the most-compatible source MUST come first. */}
            <source src="/how-it-works.mp4" type="video/mp4" />
            <source src="/how-it-works.webm" type="video/webm" />
          </video>
        )}
      </div>
    </div>
  );
}

// ── Shared scroll-frame primitives ─────────────────────────────────────

function FrameShell({
  num,
  title,
  caption,
  children,
}: {
  num: number;
  title: string;
  caption: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="mx-auto grid max-w-6xl items-center gap-8 border-t border-edge/60 px-6 py-12 first:border-t-0 md:grid-cols-2 md:gap-12 md:py-16">
      <div className="flex flex-col gap-3">
        <span className="text-xs uppercase tracking-section text-muted">
          Frame {num} of 6
        </span>
        <h3 className="text-2xl font-semibold leading-tight tracking-tight text-ink md:text-3xl">
          {title}
        </h3>
        <div className="text-sm leading-relaxed text-muted md:text-base">
          {caption}
        </div>
      </div>
      <div className="flex min-h-[260px] items-center justify-center">
        {children}
      </div>
    </div>
  );
}

// ── Frame 1: Most systems do whatever they're told ─────────────────────

function Frame1() {
  return (
    <FrameShell
      num={1}
      title="Most systems do whatever they're told."
      caption={
        <>
          A normal request flow. Whatever the agent proposes — a deploy, a
          payment, a refund, a write — the system runs it. <span className="text-ink">This is fine, until it isn&apos;t.</span>
        </>
      }
    >
      <div className="flex w-full max-w-md flex-col items-center gap-6">
        <div className="flex w-full items-center justify-between gap-3">
          <NodeBox label="Agent" tone="neutral" />
          <Arrow />
          <ProductionCluster />
        </div>
      </div>
    </FrameShell>
  );
}

// ── Frame 2: The actions that should have been governed ────────────────

function Frame2() {
  return (
    <FrameShell
      num={2}
      title="The actions that should have been governed."
      caption={
        <>
          An agent proposed deploying to 100% of production traffic — without a
          recorded approval. That single requested action is the one we&apos;ll
          follow through this entire story.
        </>
      }
    >
      <div className="flex w-full max-w-md flex-col gap-4">
        <div className="flex w-full items-center justify-between gap-3">
          <NodeBox label="Agent" tone="neutral" />
          <Arrow tone="danger" />
          <ProductionCluster />
        </div>
        <div className="rounded-xl border-2 border-dashed border-rewrite/60 bg-rewrite/5 p-4">
          <p className="font-mono text-xs uppercase tracking-section text-rewrite">
            Requested action
          </p>
          <pre className="mt-2 whitespace-pre-wrap text-xs text-ink">{`{
  service: "api",
  environment: "production",
  rampPercent: 100
}`}</pre>
        </div>
      </div>
    </FrameShell>
  );
}

// ── Frame 3: Insert a control layer ────────────────────────────────────

function Frame3() {
  return (
    <FrameShell
      num={3}
      title="Insert a control layer."
      caption={
        <>
          Before your system acts, the requested action passes through a
          control layer. The agent no longer decides what happens — the
          control layer does. The action becomes a{" "}
          <span className="font-mono text-sm text-ink">decision</span>.
        </>
      }
    >
      <div className="flex w-full max-w-md flex-col items-center gap-4">
        <div className="flex w-full items-center justify-between gap-2">
          <NodeBox label="Agent" tone="neutral" size="sm" />
          <Arrow size="sm" />
          <KernelBlock />
          <Arrow size="sm" />
          <ProductionCluster size="sm" />
        </div>
        <p className="mt-2 text-center text-xs uppercase tracking-section text-muted">
          Same scenario · routed through the kernel
        </p>
      </div>
    </FrameShell>
  );
}

// ── Frame 4: Six possible decisions (REWRITE is the iconic one) ────────

const DECISION_BRANCHES: ReadonlyArray<{
  kind: string;
  label: string;
  plain: string;
  icon: LucideIcon;
  color: string; // tailwind text- color
  bg: string;
  border: string;
}> = [
  {
    kind: "EXECUTE",
    label: "Execute",
    plain: "run as-is",
    icon: CircleCheck,
    color: "text-execute",
    bg: "bg-execute/10",
    border: "border-execute/40",
  },
  {
    kind: "REWRITE",
    label: "Rewrite",
    plain: "modify safely",
    icon: RotateCcw,
    color: "text-rewrite",
    bg: "bg-rewrite/10",
    border: "border-rewrite/40",
  },
  {
    kind: "REFUSE",
    label: "Refuse",
    plain: "block with a reason",
    icon: ShieldX,
    color: "text-refuse",
    bg: "bg-refuse/10",
    border: "border-refuse/40",
  },
  {
    kind: "DEFER",
    label: "Defer",
    plain: "wait for a signal",
    icon: Clock,
    color: "text-defer",
    bg: "bg-defer/10",
    border: "border-defer/40",
  },
  {
    kind: "ESCALATE",
    label: "Escalate",
    plain: "require a human",
    icon: UserCheck,
    color: "text-escalate",
    bg: "bg-escalate/10",
    border: "border-escalate/40",
  },
  {
    kind: "REQUEST_CONFIRMATION",
    label: "Request confirmation",
    plain: "ask the caller again",
    icon: HelpCircle,
    color: "text-confirm",
    bg: "bg-confirm/10",
    border: "border-confirm/40",
  },
];

function Frame4() {
  return (
    <FrameShell
      num={4}
      title="Six possible decisions."
      caption={
        <>
          Allow/deny isn&apos;t enough for autonomous systems. The control
          layer can <span className="font-semibold text-ink">execute, rewrite, refuse, defer, escalate, or request confirmation</span>. The
          rewrite is what makes this not a permission
          engine. Watch what it does to that 100% production deploy.
        </>
      }
    >
      <Frame4Visual />
    </FrameShell>
  );
}

function Frame4Visual() {
  const reduce = useReducedMotion();
  // Per Frame 4 discipline: animate one branch at a time, REWRITE gets the
  // longest beat (~0.9s vs ~0.6s for the others), full color only on the
  // active branch, gray ghost outlines for the rest. Cycle order puts
  // REWRITE second so the visitor's brain pivots from "okay, normal flow"
  // to "wait, what did it just do?" within the first 1.5 seconds.
  const order = [0, 1, 2, 3, 4, 5]; // EXECUTE, REWRITE, REFUSE, DEFER, ESCALATE, REQUEST_CONFIRMATION
  return (
    <div className="grid w-full max-w-md gap-2 md:grid-cols-2">
      {order.map((idx, i) => {
        const branch = DECISION_BRANCHES[idx]!;
        const isRewrite = branch.kind === "REWRITE";
        // Stagger the highlight beats. REWRITE gets a longer dwell.
        const beat = i * 0.6 + (i > 1 ? 0.3 : 0); // shift later beats by REWRITE's extra dwell
        const dwell = isRewrite ? 0.9 : 0.6;
        return (
          <motion.div
            key={branch.kind}
            // Always visible at the held state (35% opacity) — no scroll-gated
            // invisibility. The staggered highlight animation runs as flair
            // when the section enters viewport.
            initial={reduce ? false : { opacity: 0.35 }}
            whileInView={
              reduce
                ? undefined
                : {
                    opacity: [0.35, 1, 1, 0.35],
                  }
            }
            viewport={{ once: true, margin: "-50px" }}
            transition={{
              duration: dwell + 1.2,
              times: [0, 0.15, 0.15 + dwell / (dwell + 1.2), 1],
              delay: beat,
            }}
            className={`flex items-start gap-2 rounded-lg border ${branch.border} ${branch.bg} p-3`}
          >
            <branch.icon size={16} className={`${branch.color} mt-0.5 flex-shrink-0`} />
            <div className="min-w-0">
              <p className={`text-sm font-semibold ${branch.color}`}>
                {branch.label}
              </p>
              <p className="text-xs text-muted">{branch.plain}</p>
              {isRewrite ? (
                <p className="mt-1 font-mono text-[11px] text-rewrite">
                  rampPercent: 100 → 25
                </p>
              ) : null}
            </div>
          </motion.div>
        );
      })}
    </div>
  );
}

// ── Frame 5: Domain semantics, universal algebra ───────────────────────

function Frame5() {
  return (
    <FrameShell
      num={5}
      title="Domain semantics, universal algebra."
      caption={
        <>
          Packs encode the rules and state transitions of a domain. The
          kernel — and the six-decision algebra — stay universal. Same
          mechanism for payments, identity, deployments, or any AI-mediated
          domain you bring it.
        </>
      }
    >
      <div className="flex w-full max-w-md flex-col items-center gap-6">
        <div className="flex items-center justify-center gap-2">
          {(["pix", "kyc", "deployments"] as const).map((p) => (
            <div
              key={p}
              className="rounded-md border border-edge bg-surface px-3 py-1 font-mono text-xs text-muted"
            >
              {p}
            </div>
          ))}
        </div>
        <div className="flex flex-col items-center gap-1">
          <span className="text-xs text-muted">↓ snap into ↓</span>
        </div>
        <KernelBlock size="lg" />
      </div>
    </FrameShell>
  );
}

// ── Frame 6: Reconstruct why your AI system acted ──────────────────────

function Frame6() {
  return (
    <FrameShell
      num={6}
      title="Reconstruct why your AI system acted."
      caption={
        <>
          Every decision produces a structured, replay-safe audit record.
          Forensic replayability, operational accountability, causal
          traceability — built in, not bolted on.
        </>
      }
    >
      <div className="w-full max-w-md rounded-xl border border-edge bg-surface p-5 shadow-sm">
        <p className="text-xs uppercase tracking-section text-muted">
          AuditRecord (real fields, real values)
        </p>
        <pre className="mt-3 overflow-x-auto whitespace-pre-wrap rounded-md bg-canvas p-3 font-mono text-[11px] leading-relaxed text-ink">{`{
  intentHash: "sha256:9f4c…",
  intentKind: "deployment.approval.request",
  decision: "REWRITE",
  basis: ["business:QUANTITY_CAPPED"],
  rewrittenPayload: {
    rampPercent: 25
  },
  packId: "deployments-approval",
  at: "2026-05-14T11:32:08Z",
  durationMs: 0.42
}`}</pre>
      </div>
    </FrameShell>
  );
}

// ── Visual atoms ───────────────────────────────────────────────────────

function NodeBox({
  label,
  tone,
  size = "md",
}: {
  label: string;
  tone: "neutral" | "danger";
  size?: "sm" | "md";
}) {
  const padding = size === "sm" ? "px-2 py-1.5 text-[11px]" : "px-3 py-2 text-xs";
  const cls =
    tone === "danger"
      ? "border-refuse/40 bg-refuse/10 text-refuse"
      : "border-edge bg-surface text-ink";
  return (
    <div className={`rounded-md border font-mono ${cls} ${padding}`}>{label}</div>
  );
}

function Arrow({
  tone = "neutral",
  size = "md",
}: {
  tone?: "neutral" | "danger";
  size?: "sm" | "md";
}) {
  const reduce = useReducedMotion();
  const color = tone === "danger" ? "text-refuse/70" : "text-faint";
  const w = size === "sm" ? 18 : 22;
  return (
    <motion.span
      aria-hidden
      animate={reduce ? undefined : { x: [0, 4, 0] }}
      transition={{ duration: 1.6, repeat: Infinity, ease: "easeInOut" }}
      className={color}
    >
      <svg width={w} height={w} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <line x1="3" y1="12" x2="21" y2="12" />
        <polyline points="14 6 21 12 14 18" />
      </svg>
    </motion.span>
  );
}

function KernelBlock({ size = "md" }: { size?: "md" | "lg" }) {
  const dim = size === "lg" ? "h-32 w-32" : "h-20 w-20";
  return (
    <div
      className={`flex ${dim} flex-col items-center justify-center rounded-2xl bg-gradient-primary text-white shadow-xl`}
    >
      <span className="text-[10px] uppercase tracking-section text-white/80">
        control
      </span>
      <span className="text-[10px] uppercase tracking-section text-white/80">
        layer
      </span>
    </div>
  );
}

function ProductionCluster({ size = "md" }: { size?: "sm" | "md" }) {
  const padding = size === "sm" ? "px-2 py-1.5 text-[10px]" : "px-3 py-2 text-[11px]";
  return (
    <div className={`flex flex-col items-center gap-1 rounded-md border border-edge bg-surface ${padding}`}>
      <span className="font-mono text-muted">production systems</span>
      <div className="flex gap-1.5 text-base">
        <span title="database">🗄️</span>
        <span title="cloud">☁️</span>
        <span title="payments">💳</span>
        <span title="identity">👤</span>
        <span title="deployments">🚀</span>
      </div>
    </div>
  );
}
