/**
 * {{packName}} — adjudicate deployment Pack.
 *
 * Generated by `adjudicate pack init {{packName}} --template deployment`.
 *
 * Exercises four Decision outcomes against a deployment-approval
 * surface: REWRITE (clamp ramp percent), ESCALATE (production without
 * prior approval), REQUEST_CONFIRMATION (destructive rollback),
 * EXECUTE (approved deploys). Customize guards in `./policy.ts` for
 * your domain.
 */

import type { PackV0 } from "@adjudicate/core";
import { {{className}}CapabilityPlanner } from "./capabilities.js";
import { {{className}}PolicyBundle } from "./policy.js";
import type {
  {{className}}Context,
  {{className}}IntentKind,
  {{className}}State,
} from "./types.js";

export const {{className}}Pack = {
  id: "{{packName}}",
  version: "0.1.0-experimental",
  contract: "v0",
  intents: [
    "{{intentPrefix}}.deployment.request",
    "{{intentPrefix}}.deployment.rollback",
  ],
  policy: {{className}}PolicyBundle,
  planner: {{className}}CapabilityPlanner,
  basisCodes: [
    "{{intentPrefix}}.deployment.production_requires_approval",
    "{{intentPrefix}}.deployment.ramp_capped",
  ],
} as const satisfies PackV0<
  {{className}}IntentKind,
  unknown,
  {{className}}State,
  {{className}}Context
>;

export type {
  {{className}}Context,
  {{className}}Environment,
  {{className}}IntentKind,
  {{className}}State,
} from "./types.js";

export {
  MAX_RAMP_PERCENT,
  {{className}}TaintPolicy,
} from "./types.js";

export { {{className}}PolicyBundle } from "./policy.js";
export { {{className}}CapabilityPlanner, {{className}}Tools } from "./capabilities.js";
