/**
 * {{className}} deployment domain — types and taint policy.
 *
 * A deployment-approval Pack gates `deployment.request` and
 * `deployment.rollback` against environment, prior approval, and
 * ramp-percent invariants. Production deploys ESCALATE without a
 * prior approval SHA; rollbacks REQUEST_CONFIRMATION before running
 * destructive actions; ramp percentages are clamped via REWRITE.
 *
 * Generated by `adjudicate pack init {{packName}} --template deployment`.
 */

import type { TaintPolicy } from "@adjudicate/core";

// ─── Intent kinds ──────────────────────────────────────────────────────────

export type {{className}}IntentKind =
  | "{{intentPrefix}}.deployment.request"
  | "{{intentPrefix}}.deployment.rollback";

// ─── Payloads ──────────────────────────────────────────────────────────────

export interface {{className}}DeploymentRequestPayload {
  /** Git SHA being deployed. */
  readonly sha: string;
  /** Percent of traffic to receive the new version. May be REWRITTEN. */
  readonly rampPercent: number;
}

export interface {{className}}DeploymentRollbackPayload {
  /** Git SHA to roll back to. */
  readonly targetSha: string;
  readonly reason: string;
}

// ─── State ─────────────────────────────────────────────────────────────────

export type {{className}}Environment = "staging" | "production";

export interface {{className}}State {
  readonly environment: {{className}}Environment;
  readonly currentVersion: string;
  /** SHA of the most recent supervisor-approved candidate. */
  readonly lastApprovedSha?: string;
}

// ─── Context ───────────────────────────────────────────────────────────────

export interface {{className}}Context {
  readonly tenantId: string;
  readonly operatorId: string;
}

// ─── Taint policy ──────────────────────────────────────────────────────────
//
// Both deployment intents must arrive from a TRUSTED operator session —
// LLMs may suggest deploys via tools, but the kernel only honors the
// human signature. We could use `createSystemTaintPolicy` here, but
// inline is clearer when every kind is TRUSTED.

export const {{className}}TaintPolicy: TaintPolicy = {
  minimumFor(_kind) {
    return "TRUSTED";
  },
};

// ─── Domain constants ──────────────────────────────────────────────────────

/** Maximum ramp percent the policy accepts before clamping via REWRITE. */
export const MAX_RAMP_PERCENT = 100;
