/**
 * {{packName}} — adjudicate payment Pack.
 *
 * Generated by `adjudicate pack init {{packName}} --template payment`.
 *
 * Exercises five Decision outcomes against a small payment surface:
 * REFUSE (invalid amount), REWRITE (refund > original), ESCALATE (large
 * refund), DEFER (awaiting provider webhook), EXECUTE (happy-path
 * confirm/refund). Customize guards in `./policy.ts` for your domain.
 */

import type { PackV0 } from "@adjudicate/core";
import { {{className}}CapabilityPlanner } from "./capabilities.js";
import { {{className}}PolicyBundle } from "./policy.js";
import {
  PAYMENT_CONFIRMATION_SIGNAL,
  type {{className}}Context,
  type {{className}}IntentKind,
  type {{className}}Payment,
  type {{className}}State,
} from "./types.js";

/**
 * Reconstitute a `{{className}}State` from JSON-serializable form.
 *
 * The runtime state uses `Map<string, Payment>` for `payments`, which
 * doesn't survive `JSON.stringify`. Scenario fixtures + audit replay
 * payloads call this to convert `{ payments: { [id]: Payment } }` back
 * into the Map shape policy guards expect.
 */
export function rehydrate{{className}}State(raw: unknown): {{className}}State {
  if (typeof raw === "object" && raw !== null && "payments" in raw) {
    const payments = (raw as { payments: unknown }).payments;
    if (payments instanceof Map) {
      return { payments: payments as ReadonlyMap<string, {{className}}Payment> };
    }
    if (typeof payments === "object" && payments !== null) {
      return {
        payments: new Map(
          Object.entries(payments as Record<string, {{className}}Payment>),
        ),
      };
    }
  }
  return { payments: new Map() };
}

export const {{className}}Pack = {
  id: "{{packName}}",
  version: "0.1.0-experimental",
  contract: "v0",
  intents: [
    "{{intentPrefix}}.payment.create",
    "{{intentPrefix}}.payment.confirm",
    "{{intentPrefix}}.payment.refund",
  ],
  policy: {{className}}PolicyBundle,
  planner: {{className}}CapabilityPlanner,
  basisCodes: [
    "{{intentPrefix}}.payment.amount_invalid",
    "{{intentPrefix}}.payment.not_found",
    "{{intentPrefix}}.payment.already_refunded",
  ],
  signals: [PAYMENT_CONFIRMATION_SIGNAL],
  rehydrateState: rehydrate{{className}}State,
} as const satisfies PackV0<
  {{className}}IntentKind,
  unknown,
  {{className}}State,
  {{className}}Context
>;

export type {
  {{className}}Context,
  {{className}}IntentKind,
  {{className}}Payment,
  {{className}}PaymentStatus,
  {{className}}State,
} from "./types.js";

export {
  ESCALATE_REFUND_THRESHOLD_CENTAVOS,
  PAYMENT_CONFIRMATION_SIGNAL,
  PAYMENT_DEFAULT_DEFER_TIMEOUT_MS,
  {{className}}TaintPolicy,
} from "./types.js";

export { {{className}}PolicyBundle } from "./policy.js";
export { {{className}}CapabilityPlanner, {{className}}Tools } from "./capabilities.js";
