/**
 * {{className}} payment domain — types and taint policy.
 *
 * A payment Pack tracks the create → confirm → refund lifecycle. Each
 * intent kind takes a payload that the policy validates; the State holds
 * payment records keyed by id; the TaintPolicy controls which intents
 * may be LLM-proposed (UNTRUSTED) versus system-only (TRUSTED).
 *
 * Generated by `adjudicate pack init {{packName}} --template payment`.
 */

import { createSystemTaintPolicy } from "@adjudicate/primitives";

// ─── Intent kinds ──────────────────────────────────────────────────────────

export type {{className}}IntentKind =
  | "{{intentPrefix}}.payment.create"
  | "{{intentPrefix}}.payment.confirm"
  | "{{intentPrefix}}.payment.refund";

// ─── Payloads ──────────────────────────────────────────────────────────────

export interface {{className}}PaymentCreatePayload {
  /** Amount in centavos (integer). Never floats — see CLAUDE.md hard rule #2. */
  readonly amountCentavos: number;
  /** Free-text payer identifier. Adopters often replace with a CPF/CNPJ. */
  readonly payerRef: string;
}

export interface {{className}}PaymentConfirmPayload {
  readonly paymentId: string;
  /** Provider's transaction id — used as idempotency key for the webhook. */
  readonly providerTxId: string;
}

export interface {{className}}PaymentRefundPayload {
  readonly paymentId: string;
  /** Refund amount in centavos. May be REWRITTEN if it exceeds the original. */
  readonly refundCentavos: number;
  readonly reason: string;
}

// ─── State ─────────────────────────────────────────────────────────────────

export type {{className}}PaymentStatus =
  | "pending"
  | "confirmed"
  | "refunded"
  | "failed";

export interface {{className}}Payment {
  readonly id: string;
  readonly amountCentavos: number;
  readonly status: {{className}}PaymentStatus;
}

export interface {{className}}State {
  /** All payments, keyed by payment id. Adopter persistence is out of scope. */
  readonly payments: ReadonlyMap<string, {{className}}Payment>;
}

// ─── Context ───────────────────────────────────────────────────────────────

export interface {{className}}Context {
  readonly tenantId: string;
}

// ─── Taint policy ──────────────────────────────────────────────────────────
//
// `payment.confirm` arrives from the provider webhook — TRUSTED only.
// `payment.create` and `payment.refund` may be LLM-proposed.

export const {{className}}TaintPolicy = createSystemTaintPolicy({
  systemOnlyKinds: ["{{intentPrefix}}.payment.confirm"],
});

// ─── Domain constants ──────────────────────────────────────────────────────

/**
 * Refunds at or above this threshold (in centavos) ESCALATE to a supervisor.
 * R$ 1,000.00 by default.
 */
export const ESCALATE_REFUND_THRESHOLD_CENTAVOS = 100_000;

/**
 * Signal name the deferred `payment.create` intent resumes on.
 */
export const PAYMENT_CONFIRMATION_SIGNAL = "payment.confirmed";

/**
 * Default deadline for a pending payment before adopters give up on the
 * webhook signal. Passed to `decisionDefer(timeoutMs)`.
 */
export const PAYMENT_DEFAULT_DEFER_TIMEOUT_MS = 15 * 60 * 1000;
