import { describe, expect, it } from "vitest";
import { assertPackConformance } from "@adjudicate/core";
import { {{className}}Pack } from "../src/index.js";

/**
 * Conformance test — runs the kernel's `assertPackConformance` against
 * the Pack export. Generated by `adjudicate pack init --template payment`.
 * Add domain-specific tests alongside as your Pack grows.
 */
describe("{{packName}} — conformance", () => {
  it("passes kernel pack conformance", () => {
    expect(() => assertPackConformance({{className}}Pack)).not.toThrow();
  });

  it("declares the expected payment intent kinds", () => {
    expect({{className}}Pack.intents).toContain(
      "{{intentPrefix}}.payment.create",
    );
    expect({{className}}Pack.intents).toContain(
      "{{intentPrefix}}.payment.confirm",
    );
    expect({{className}}Pack.intents).toContain(
      "{{intentPrefix}}.payment.refund",
    );
  });

  it("uses contract v0", () => {
    expect({{className}}Pack.contract).toBe("v0");
  });

  it("declares basisCodes that the policy may emit", () => {
    expect({{className}}Pack.basisCodes.length).toBeGreaterThan(0);
  });

  it("declares the payment-confirmed defer signal", () => {
    expect({{className}}Pack.signals).toContain("payment.confirmed");
  });

  it("has a non-empty business guard list", () => {
    expect({{className}}Pack.policy.business.length).toBeGreaterThan(0);
  });
});
